[workspace]
authors = ["Ryan <18477649+Ryul0rd@users.noreply.github.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "vulkan-mojo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
bindgen = "python3 bindgen.py"
compile = "mojo precompile vk -o vk.mojoc"
build = {depends-on = ["bindgen", "compile"]}

[dependencies]
mojo = "==1.0.0b3.dev2026070506"
python = ">=3.10,<3.11"
